name: "instagram_analytics"
version: "1.0.0"
config-version: 2

profile: "instagram_analytics"

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]

models:
  instagram_analytics:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    mart:
      +materialized: table
